[build]
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/ziwei-analysis"
  to = "/.netlify/functions/ziwei-analysis"
  status = 200

[[redirects]]
  from = "/api/holland-test"
  to = "/.netlify/functions/holland-test"
  status = 200

[[redirects]]
  from = "/api/combined-analysis"
  to = "/.netlify/functions/combined-analysis"
  status = 200

# 兼容原有API路径
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
